// Generates package data files from astronomical algorithms.
// Usage:
//   swift run GenerateData --lunar-years > Sources/LunarCore/Data/LunarYearData.swift
//   swift run GenerateData --solar-terms > Sources/LunarCore/Data/SolarTermYearData.swift

import Foundation
import LunarCore
#if canImport(Darwin)
import Darwin
#elseif canImport(Glibc)
import Glibc
#endif

let startYear = 1900
let endYear = 2100

// HKO-authoritative historical corrections for early-20th-century windows where
// the astronomical compilation path differs from the official promulgated calendar.
// These values keep generated data aligned with Hong Kong Observatory year tables.
let historicalLunarYearOverrides: [Int: UInt32] = [
    1914: 0x692AF400,
    1915: 0x5AA01D00,
    1916: 0x6B500700,
    1920: 0x24B82900,
]

enum OutputKind {
    case lunarYears
    case solarTerms
}

func writeStderr(_ message: String) {
    FileHandle.standardError.write(Data((message + "\n").utf8))
}

func parseOutputKind() -> OutputKind {
    let args = CommandLine.arguments.dropFirst()
    if args.contains("--solar-terms") {
        return .solarTerms
    }
    return .lunarYears
}

// Encode a single lunar year into UInt32 per SPEC 4.3 bit layout:
// [31]    : reserved (0)
// [30-19] : 12 bits — month sizes (1=30d, 0=29d), bit30=M1..bit19=M12
// [18-15] : 4 bits  — leap month (0=none, 1-12)
// [14]    : 1 bit   — leap month size (1=30d, 0=29d)
// [13-9]  : 5 bits  — CNY day (1-31)
// [8]     : 1 bit   — CNY month (0=Jan, 1=Feb)
// [7-0]   : 8 bits  — reserved (0)
func encode(_ raw: LunarYearRaw) -> UInt32 {
    var bits: UInt32 = 0

    // Month sizes: 12 regular months (non-leap)
    let regularMonths = raw.months.filter { !$0.isLeapMonth }
    for (i, m) in regularMonths.enumerated() where i < 12 {
        if m.dayCount == 30 {
            bits |= 1 << UInt32(30 - i)
        }
    }

    // Leap month info
    if let leapMonth = raw.leapMonth {
        bits |= UInt32(leapMonth) << 15
        if let leapMonthRaw = raw.months.first(where: { $0.isLeapMonth }) {
            if leapMonthRaw.dayCount == 30 {
                bits |= 1 << 14
            }
        }
    }

    // CNY date
    let cny = raw.chineseNewYear
    bits |= UInt32(cny.day) << 9
    if cny.month == 2 {
        bits |= 1 << 8
    }

    return bits
}

func generateLunarYears() {
    var encoded: [UInt32] = []
    var failures: [Int] = []

    for year in startYear...endYear {
        guard let raw = LunarCalendarComputer.computeLunarYear(year: year) else {
            writeStderr("ERROR: failed to compute year \(year)")
            failures.append(year)
            encoded.append(0)
            continue
        }
        let computed = encode(raw)
        let value = historicalLunarYearOverrides[year] ?? computed
        if value != computed {
            writeStderr("NOTE: applied HKO historical override for \(year)")
        }
        encoded.append(value)
    }

    if !failures.isEmpty {
        writeStderr("FATAL: \(failures.count) year(s) failed: \(failures)")
        exit(1)
    }

    writeStderr("")
    writeStderr("=== 2020-2030 Lunar Year Summary ===")
    for year in 2020...2030 {
        guard let raw = LunarCalendarComputer.computeLunarYear(year: year) else {
            writeStderr("\(year): FAILED")
            continue
        }
        let cny = raw.chineseNewYear
        let leap = raw.leapMonth.map { "leap \($0)" } ?? "no leap"
        let monthSizes = raw.months.map { m -> String in
            let prefix = m.isLeapMonth ? "L" : "M"
            return "\(prefix)\(m.month):\(m.dayCount)"
        }.joined(separator: " ")
        let packed = encode(raw)
        writeStderr(String(format: "%d: CNY=%d-%02d-%02d, %@, 0x%08X",
                           year, cny.year, cny.month, cny.day, leap, packed))
        writeStderr("  \(monthSizes)")
    }
    writeStderr("====================================")

    print("// Auto-generated by GenerateData. DO NOT EDIT.")
    print("// Lunar year data for \(startYear)-\(endYear) (\(encoded.count) years).")
    print("// Each UInt32 encodes month sizes, leap month, and CNY date.")
    print("// See SPEC.md 4.3 for bit layout.")
    print("")
    print("enum LunarYearData: Sendable, Equatable, Hashable {")
    print("")
    print("    static let startYear = \(startYear)")
    print("    static let endYear = \(endYear)")
    print("")
    print("    // \(encoded.count) entries, index 0 = year \(startYear)")
    print("    static let table: [UInt32] = [")

    for (i, value) in encoded.enumerated() {
        let year = startYear + i
        let hex = String(format: "0x%08X", value)
        let comma = i < encoded.count - 1 ? "," : ""
        print("        \(hex)\(comma) // \(year)")
    }

    print("    ]")
    print("}")
    print("")
}

func generateSolarTerms() {
    var encoded: [UInt16] = []
    var failures: [(Int, SolarTerm)] = []

    for year in startYear...endYear {
        for term in SolarTerm.allCases {
            guard let date = SolarTermCalc.solarTermDate(term: term, year: year) else {
                writeStderr("ERROR: failed to compute \(term) for year \(year)")
                failures.append((year, term))
                encoded.append(0)
                continue
            }

            let packed = UInt16((date.month << 8) | date.day)
            encoded.append(packed)
        }
    }

    if !failures.isEmpty {
        writeStderr("FATAL: \(failures.count) solar term entries failed")
        exit(1)
    }

    writeStderr("")
    writeStderr("=== 2024-2026 Solar Term Summary ===")
    for year in 2024...2026 {
        let summary = SolarTerm.allCases.compactMap { term -> String? in
            guard let date = SolarTermCalc.solarTermDate(term: term, year: year) else {
                return nil
            }
            return "\(term.chineseName)=\(String(format: "%02d-%02d", date.month, date.day))"
        }.joined(separator: " ")
        writeStderr("\(year): \(summary)")
    }
    writeStderr("====================================")

    print("// Auto-generated by GenerateData. DO NOT EDIT.")
    print("// Solar term date data for \(startYear)-\(endYear) (\(endYear - startYear + 1) years × \(SolarTerm.allCases.count) terms).")
    print("// Each UInt16 packs month/day as 0xMMDD, ordered by SolarTerm.allCases.")
    print("")
    print("enum SolarTermYearData: Sendable, Equatable, Hashable {")
    print("")
    print("    static let startYear = \(startYear)")
    print("    static let endYear = \(endYear)")
    print("    static let termsPerYear = \(SolarTerm.allCases.count)")
    print("")
    print("    // Flat table: (year - startYear) * termsPerYear + term.rawValue")
    print("    static let table: [UInt16] = [")

    for (index, value) in encoded.enumerated() {
        let year = startYear + index / SolarTerm.allCases.count
        let termIndex = index % SolarTerm.allCases.count
        let term = SolarTerm(rawValue: termIndex)!
        let hex = String(format: "0x%04X", value)
        let comma = index < encoded.count - 1 ? "," : ""
        print("        \(hex)\(comma) // \(year) \(term.chineseName)")
    }

    print("    ]")
    print("}")
    print("")
}

switch parseOutputKind() {
case .lunarYears:
    generateLunarYears()
case .solarTerms:
    generateSolarTerms()
}
